 package problem_002;

//@Problem:
//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

import java.io.PrintStream;
//import java.util.Scanner;

public class P_002 {
	public static final int RANGE = 4000000;

	public P_002() {
		out = new PrintStream(System.out);
	}

	PrintStream out;

	void start() {
//		Scanner in = new Scanner(System.in);
//		int range = in.nextInt();
		
		int counter = 0;
		int sum = 0;
		int[] fibM = new int[2];
		fibM[0] = 1;
		fibM[1] = 1;

		while (counter <= RANGE) {
			counter = fibM[0] + fibM[1];
			if (counter > RANGE) {
				break;
			}
			if (counter % 2 == 0) {
				sum += counter;
			}
			fibM[0] = fibM[1];
			fibM[1] = counter;
		}
		out.printf("%d", sum);
	}

	public static void main(String[] args) {
		new P_002().start();
	}

}
